spring:
  application:
    name: guestbook-service
  task:
    execution:
      pool:
        max-size: 160
  r2dbc:
    url: r2dbc:mysql://localhost:3306/guestbook_service
    username: root
    password: password
    pool:
      max-size: 150
  flyway:
    baseline-on-migrate: true
    baseline-version: 3
    url: jdbc:mysql://localhost:3306/guestbook_service
    user: root
    password: password

logging:
  level:
    #    org.springframework.r2dbc.core: debug
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
